// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:darna/features/auth/models/app_user.dart';
import 'package:darna/features/chat/models/chat_message.dart';
import 'package:darna/features/listings/models/property.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(PropertyAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(PropertyAdapter());
  }
}
